name: fast_cache_network_image
description: A flutter package to cache network image,lottie and videos easily.You can add beautiful loaders, percentage indicators and error builder.
version: 1.0.11
homepage: https://github.com/deepak07082/fast_cached_network_image

topics:
  - cache
  - image
  - photo
  - download
  - network


environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  lottie: ^3.3.2
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  uuid: ^4.5.2
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
